// <auto-generated />
using System;
using DALLibrary.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DALLibrary.Migrations
{
    [DbContext(typeof(BookRentalContext))]
    [Migration("20260518085344_MembershipActive")]
    partial class MembershipActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModelLibrary.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "J.K. Rowling",
                            CategoryId = 1,
                            ISBN = "978-0439708180",
                            PublishedYear = 1997,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Frank Herbert",
                            CategoryId = 2,
                            ISBN = "978-0441172719",
                            PublishedYear = 1965,
                            Title = "Dune"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Arthur Conan Doyle",
                            CategoryId = 3,
                            ISBN = "978-0553212419",
                            PublishedYear = 1892,
                            Title = "Sherlock Holmes"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "James Clear",
                            CategoryId = 4,
                            ISBN = "978-0735211292",
                            PublishedYear = 2018,
                            Title = "Atomic Habits"
                        });
                });

            modelBuilder.Entity("ModelLibrary.Models.BookCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Non-Fiction"
                        });
                });

            modelBuilder.Entity("ModelLibrary.Models.BookCopy", b =>
                {
                    b.Property<int>("CopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CopyId"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("CopyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CopyStatus")
                        .HasColumnType("integer");

                    b.HasKey("CopyId");

                    b.HasIndex("BookId");

                    b.ToTable("BookCopies");

                    b.HasData(
                        new
                        {
                            CopyId = 1,
                            AddedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookId = 1,
                            CopyNumber = "HP-001",
                            CopyStatus = 0
                        },
                        new
                        {
                            CopyId = 2,
                            AddedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookId = 1,
                            CopyNumber = "HP-002",
                            CopyStatus = 0
                        },
                        new
                        {
                            CopyId = 3,
                            AddedDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookId = 2,
                            CopyNumber = "DU-001",
                            CopyStatus = 0
                        },
                        new
                        {
                            CopyId = 4,
                            AddedDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookId = 3,
                            CopyNumber = "SH-001",
                            CopyStatus = 0
                        },
                        new
                        {
                            CopyId = 5,
                            AddedDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookId = 4,
                            CopyNumber = "AH-001",
                            CopyStatus = 0
                        });
                });

            modelBuilder.Entity("ModelLibrary.Models.BookDamageHistory", b =>
                {
                    b.Property<int>("DamageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DamageId"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DamageDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("DamageDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportedUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("DamageId");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("ReportedUserId");

                    b.ToTable("BookDamageHistories");
                });

            modelBuilder.Entity("ModelLibrary.Models.Borrowing", b =>
                {
                    b.Property<int>("BorrowingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BorrowingId"));

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("CopyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("BorrowingId");

                    b.HasIndex("CopyId");

                    b.HasIndex("MemberId");

                    b.ToTable("Borrowings");
                });

            modelBuilder.Entity("ModelLibrary.Models.Fine", b =>
                {
                    b.Property<int>("FineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FineId"));

                    b.Property<int>("BorrowingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PaidStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.HasKey("FineId");

                    b.HasIndex("BorrowingId");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("ModelLibrary.Models.FinePayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("FineId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PaidDate")
                        .HasColumnType("timestamp");

                    b.HasKey("PaymentId");

                    b.HasIndex("FineId");

                    b.ToTable("FinePayments");
                });

            modelBuilder.Entity("ModelLibrary.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MembershipEndDate")
                        .HasColumnType("timestamp");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MembershipStartDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("MembershipStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MemberId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MembershipId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            Email = "alice@example.com",
                            IsActive = true,
                            MembershipEndDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipId = 2,
                            MembershipStartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStatus = 0,
                            Name = "Alice Smith",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            MemberId = 2,
                            Email = "bob@example.com",
                            IsActive = true,
                            MembershipStatus = 2,
                            Name = "Bob Jones",
                            PhoneNumber = "0987654321"
                        });
                });

            modelBuilder.Entity("ModelLibrary.Models.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MembershipId"));

                    b.Property<int>("BorrowDaysLimit")
                        .HasColumnType("integer");

                    b.Property<int>("BorrowLimit")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MembershipName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MembershipPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("MembershipId");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            MembershipId = 1,
                            BorrowDaysLimit = 7,
                            BorrowLimit = 2,
                            IsActive = true,
                            MembershipName = "Basic",
                            MembershipPrice = 500m
                        },
                        new
                        {
                            MembershipId = 2,
                            BorrowDaysLimit = 14,
                            BorrowLimit = 5,
                            IsActive = true,
                            MembershipName = "Premium",
                            MembershipPrice = 1500m
                        },
                        new
                        {
                            MembershipId = 3,
                            BorrowDaysLimit = 30,
                            BorrowLimit = 10,
                            IsActive = true,
                            MembershipName = "Elite",
                            MembershipPrice = 3000m
                        });
                });

            modelBuilder.Entity("ModelLibrary.Models.MembershipPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("MembershipId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp");

                    b.HasKey("PaymentId");

                    b.HasIndex("MemberId");

                    b.HasIndex("MembershipId");

                    b.ToTable("MembershipPayments");
                });

            modelBuilder.Entity("ModelLibrary.Models.Book", b =>
                {
                    b.HasOne("ModelLibrary.Models.BookCategory", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ModelLibrary.Models.BookCopy", b =>
                {
                    b.HasOne("ModelLibrary.Models.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("ModelLibrary.Models.BookDamageHistory", b =>
                {
                    b.HasOne("ModelLibrary.Models.BookCopy", "BookCopy")
                        .WithMany("DamageHistories")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLibrary.Models.Member", "ReportedUser")
                        .WithMany("DamageHistories")
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("ReportedUser");
                });

            modelBuilder.Entity("ModelLibrary.Models.Borrowing", b =>
                {
                    b.HasOne("ModelLibrary.Models.BookCopy", "BookCopy")
                        .WithMany("Borrowings")
                        .HasForeignKey("CopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelLibrary.Models.Member", "Member")
                        .WithMany("Borrowings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ModelLibrary.Models.Fine", b =>
                {
                    b.HasOne("ModelLibrary.Models.Borrowing", "Borrowing")
                        .WithMany("Fines")
                        .HasForeignKey("BorrowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Borrowing");
                });

            modelBuilder.Entity("ModelLibrary.Models.FinePayment", b =>
                {
                    b.HasOne("ModelLibrary.Models.Fine", "Fine")
                        .WithMany("FinePayments")
                        .HasForeignKey("FineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fine");
                });

            modelBuilder.Entity("ModelLibrary.Models.Member", b =>
                {
                    b.HasOne("ModelLibrary.Models.Membership", "Membership")
                        .WithMany("Members")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("ModelLibrary.Models.MembershipPayment", b =>
                {
                    b.HasOne("ModelLibrary.Models.Member", "Member")
                        .WithMany("MembershipPayments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLibrary.Models.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("ModelLibrary.Models.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("ModelLibrary.Models.BookCategory", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("ModelLibrary.Models.BookCopy", b =>
                {
                    b.Navigation("Borrowings");

                    b.Navigation("DamageHistories");
                });

            modelBuilder.Entity("ModelLibrary.Models.Borrowing", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("ModelLibrary.Models.Fine", b =>
                {
                    b.Navigation("FinePayments");
                });

            modelBuilder.Entity("ModelLibrary.Models.Member", b =>
                {
                    b.Navigation("Borrowings");

                    b.Navigation("DamageHistories");

                    b.Navigation("MembershipPayments");
                });

            modelBuilder.Entity("ModelLibrary.Models.Membership", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
